### ISSUE TITLE
Task manager

### ISSUE THREAD

**Issue by balazsorban44** [IT2810/it2810-webutvikling-h18-prosjekt-3-09#1]
Implement a TO-DO list.

- [x] View items
- [x] Add new item
- [x] Edit existing item
- [x] Delete item
- [ ] Edit order

**Comment by balazsorban44** [comment]
> Currently using state instead of AsyncStorage. This needs to be changed in the future.

Look at #9 , I wrote a detailed solution to this. 🎉

**Comment by haavarol** [comment]
Now functioning as intended with `AsyncStorage` as stated in #9. Styling awaits decision on a common theme/styling.
