### ISSUE TITLE
Common theme/styling

### ISSUE THREAD

**Issue by balazsorban44** [IT2810/it2810-webutvikling-h18-prosjekt-3-09#14]
This issue is connected to #7 . Should we find a UI library to style all of our components, or should we write our own stylings?

**Comment by haavarol** [comment]
If we can find a good UI library, I say go for it! No need to reinvent the wheel.

**Comment by kristhus** [comment]
I agree with finding a library to get a more streamlined and shared styling between features

**Comment by kristhus** [comment]
> @haavarol I see you added [React Native Elements](https://react-native-training.github.io/react-native-elements/) in this commit: [41aa508](https://github.com/IT2810/it2810-webutvikling-h18-prosjekt-3-09/commit/41aa508fc66fff42171bc4aca2b8558fbf6b25e6)
> It looks like it supports both 🍏 and 🤖.
> So, I guess we can use that. 👍 What do you think @kristhus?

Looked through its supported components. Looks highly relevant to the motivation manager #4

**Comment by balazsorban44** [comment]
I guess we agreed to use it then. I am closing this issue.
