### ISSUE TITLE
Write documentation 📚

### ISSUE THREAD

**Issue by haavarol** [IT2810/it2810-webutvikling-h18-prosjekt-3-09#3]
- [x] Add README.md

**Comment by balazsorban44** [comment]
What should we  document in the `README.md`? @haavarol @kristhus

**Comment by haavarol** [comment]
> What should we document in the `README.md`? @haavarol @kristhus

I think we can safely use the `README.md` from our previous project as a starting point for this one. It seems to me that the only thing they ask differently this time is that we include, and explain, all third party libraries we have used.
