### ISSUE TITLE
Get familiar with the technologies 🤖

### ISSUE THREAD

**Issue by haavarol** [IT2810/it2810-webutvikling-h18-prosjekt-3-09#6]
- [x] [React Native](https://facebook.github.io/react-native/)
- [x] [AsyncStorage](https://facebook.github.io/react-native/docs/asyncstorage)
- [x] [Jest](https://jestjs.io/)

**Comment by balazsorban44** [comment]
@haavarol @kristhus Look at Jest :black_joker: as well for the testing.
